[package]
name = "xem-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sdl3-sys.workspace = true
raw-window-handle.workspace = true
wgpu.workspace = true
pollster.workspace = true
png.workspace = true
xem-render = { path = "../xem-render" }
xem-ui = { path = "../xem-ui" }
xem-settings = { path = "../xem-settings" }
